// Residue and element tables shared by the BCIF and PQR readers.
type PolymerKind = "protein" | "rna" | "dna" | "other";

// Upper-cased mmCIF type_symbol -> atomic number, ported from Mol* 5.11.0's
// MIT-licensed AtomicNumbers (mol-model/structure/model/properties/atomic/
// measures.js); D and T are hydrogen. Unlisted symbols read 0 (unknown).
export const ELEMENT: Readonly<Record<string, number>> = {
  H: 1,
  D: 1,
  T: 1,
  HE: 2,
  LI: 3,
  BE: 4,
  B: 5,
  C: 6,
  N: 7,
  O: 8,
  F: 9,
  NE: 10,
  NA: 11,
  MG: 12,
  AL: 13,
  SI: 14,
  P: 15,
  S: 16,
  CL: 17,
  AR: 18,
  K: 19,
  CA: 20,
  SC: 21,
  TI: 22,
  V: 23,
  CR: 24,
  MN: 25,
  FE: 26,
  CO: 27,
  NI: 28,
  CU: 29,
  ZN: 30,
  GA: 31,
  GE: 32,
  AS: 33,
  SE: 34,
  BR: 35,
  KR: 36,
  RB: 37,
  SR: 38,
  Y: 39,
  ZR: 40,
  NB: 41,
  MO: 42,
  TC: 43,
  RU: 44,
  RH: 45,
  PD: 46,
  AG: 47,
  CD: 48,
  IN: 49,
  SN: 50,
  SB: 51,
  TE: 52,
  I: 53,
  XE: 54,
  CS: 55,
  BA: 56,
  LA: 57,
  CE: 58,
  PR: 59,
  ND: 60,
  PM: 61,
  SM: 62,
  EU: 63,
  GD: 64,
  TB: 65,
  DY: 66,
  HO: 67,
  ER: 68,
  TM: 69,
  YB: 70,
  LU: 71,
  HF: 72,
  TA: 73,
  W: 74,
  RE: 75,
  OS: 76,
  IR: 77,
  PT: 78,
  AU: 79,
  HG: 80,
  TL: 81,
  PB: 82,
  BI: 83,
  PO: 84,
  AT: 85,
  RN: 86,
  FR: 87,
  RA: 88,
  AC: 89,
  TH: 90,
  PA: 91,
  U: 92,
  NP: 93,
  PU: 94,
  AM: 95,
  CM: 96,
  BK: 97,
  CF: 98,
  ES: 99,
  FM: 100,
  MD: 101,
  NO: 102,
  LR: 103,
  RF: 104,
  DB: 105,
  SG: 106,
  BH: 107,
  HS: 108,
  MT: 109,
};

// Chemical-component name sets ported from Mol* 5.11.0's MIT-licensed
// mol-model/structure/model/types.js (AminoAcidNamesL/D, RnaBaseNames,
// DnaBaseNames), used to classify each residue by its `comp` (label_comp_id)
// so trace/cartoon consumers can pick guide atoms without re-deriving this.
export const AMINO_ACID_NAMES = new Set([
  "HIS",
  "ARG",
  "LYS",
  "ILE",
  "PHE",
  "LEU",
  "TRP",
  "ALA",
  "MET",
  "PRO",
  "CYS",
  "ASN",
  "VAL",
  "GLY",
  "SER",
  "GLN",
  "TYR",
  "ASP",
  "GLU",
  "THR",
  "SEC",
  "PYL",
  "UNK",
  "MSE",
  "SEP",
  "TPO",
  "PTR",
  "PCA",
  "HYP",
  "HSD",
  "HSE",
  "HSP",
  "LSN",
  "ASPP",
  "GLUP",
  "HID",
  "HIE",
  "HIP",
  "LYN",
  "ASH",
  "GLH",
  "DAL",
  "DAR",
  "DSG",
  "DAS",
  "DCY",
  "DGL",
  "DGN",
  "DHI",
  "DIL",
  "DLE",
  "DLY",
  "MED",
  "DPN",
  "DPR",
  "DSN",
  "DTH",
  "DTR",
  "DTY",
  "DVA",
  "DNE",
]);
const RNA_BASE_NAMES = new Set(["A", "C", "T", "G", "I", "U", "N"]);
const DNA_BASE_NAMES = new Set(["DA", "DC", "DT", "DG", "DI", "DU", "DN"]);
export const polymerKind = (comp: string): PolymerKind => {
  const name = comp.toUpperCase();
  if (AMINO_ACID_NAMES.has(name)) return "protein";
  if (RNA_BASE_NAMES.has(name)) return "rna";
  if (DNA_BASE_NAMES.has(name)) return "dna";
  return "other";
};
